export type SeedMenuItem = {
  name: string;
  category: string;
  price: string;
  description: string;
  tag?: string;
};

export const menuCategories = ["Breads & Parathas", "Main Course / Sabji", "Maggi & Snacks", "Rice, Combos & Thalis", "Extras & Beverages", "Vrat Items"] as const;

export const menuSeed: SeedMenuItem[] = [
  { name: "Aloo Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹50", description: "Tawa-roasted paratha stuffed with spiced potato." },
  { name: "Aloo Pyaaz Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹65", description: "Potato and onion stuffed paratha, cooked on the tawa." },
  { name: "Masala Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹70", description: "Layered paratha with our everyday masala." },
  { name: "Lachha Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹75", description: "Flaky, hand-layered paratha from the tawa." },
  { name: "Mix Veg. Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹85", description: "Seasonal vegetables folded into a crisp paratha." },
  { name: "Paneer Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹95", description: "Soft paneer filling with gentle spices." },
  { name: "Paneer Pyaaz Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹85", description: "Paneer and onion filling, fresh from the tawa." },
  { name: "Plain Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹25", description: "Simple, crisp, everyday paratha." },
  { name: "Plain Desi Ghee Paratha (1 pcs.)", category: "Breads & Parathas", price: "₹40", description: "Plain paratha finished with desi ghee." },
  { name: "Tawa Roti (1 pcs.)", category: "Breads & Parathas", price: "₹12", description: "Soft roti cooked fresh on the tawa." },
  { name: "Desi Ghee Tawa Roti (1 pcs.)", category: "Breads & Parathas", price: "₹15", description: "Fresh tawa roti with a desi ghee finish." },
  { name: "Butter Tawa Roti (1 pcs.)", category: "Breads & Parathas", price: "₹17", description: "Tawa roti finished with butter." },
  { name: "Aloo Jeera", category: "Main Course / Sabji", price: "Half ₹80 · Full ₹130", description: "Potatoes tossed with cumin and homestyle spices." },
  { name: "Baingan Bharta", category: "Main Course / Sabji", price: "Half ₹100 · Full ₹160", description: "Roasted eggplant cooked down with tomato and spices." },
  { name: "Aloo Gobhi", category: "Main Course / Sabji", price: "Half ₹100 · Full ₹165", description: "Potato and cauliflower sabji, cooked the ghar-style way." },
  { name: "Mix Veg.", category: "Main Course / Sabji", price: "Half ₹135 · Full ₹195", description: "A colourful mix of vegetables in a light masala." },
  { name: "Lauki Ke Kofte", category: "Main Course / Sabji", price: "Half ₹95 · Full ₹160", description: "Soft bottle-gourd koftas in a comforting gravy." },
  { name: "Matar Mashroom", category: "Main Course / Sabji", price: "Half ₹150 · Full ₹275", description: "Green peas and mushrooms in a home-style gravy." },
  { name: "Matar Paneer", category: "Main Course / Sabji", price: "Half ₹165 · Full ₹230", description: "Paneer and peas in a gently spiced tomato gravy." },
  { name: "Paneer Bhurji", category: "Main Course / Sabji", price: "Half ₹195 · Full ₹270", description: "Crumbled paneer with onion, tomato and fresh coriander." },
  { name: "Kadhai Paneer", category: "Main Course / Sabji", price: "Half ₹155 · Full ₹240", description: "Paneer with peppers and roasted kadhai masala." },
  { name: "Sahi Paneer", category: "Main Course / Sabji", price: "Half ₹185 · Full ₹300", description: "Paneer in a smooth, mildly spiced gravy." },
  { name: "Paneer Butter Masala", category: "Main Course / Sabji", price: "Half ₹195 · Full ₹300", description: "Paneer in a buttery tomato masala." },
  { name: "Dal Fry", category: "Main Course / Sabji", price: "Half ₹80 · Full ₹150", description: "Yellow dal finished with a fresh tadka." },
  { name: "Desi Ghee Dal Tadka", category: "Main Course / Sabji", price: "Half ₹90 · Full ₹165", description: "Dal with a fragrant desi ghee tempering." },
  { name: "Plain Maggi", category: "Maggi & Snacks", price: "₹60", description: "Classic Maggi, made hot to order." },
  { name: "Veg. Maggi", category: "Maggi & Snacks", price: "₹80", description: "Maggi tossed with fresh vegetables." },
  { name: "Veg. Fried Maggi", category: "Maggi & Snacks", price: "₹95", description: "Wok-tossed Maggi with vegetables and spice." },
  { name: "Veg. Fried Butter Maggi", category: "Maggi & Snacks", price: "₹110", description: "Fried Maggi with vegetables and a buttery finish." },
  { name: "Mix Veg. Besan Chilla", category: "Maggi & Snacks", price: "1 pc ₹70 · 2 pcs ₹120", description: "Savoury besan chilla packed with vegetables." },
  { name: "Peanut Veg. Poha", category: "Maggi & Snacks", price: "Half ₹65 · Full ₹110", description: "Light poha with peanuts, vegetables and lemon." },
  { name: "Veg. Vermiceli (Javain)", category: "Maggi & Snacks", price: "Half ₹70 · Full ₹105", description: "Tempered vegetable vermicelli for a light meal." },
  { name: "Plain Bread Pakoda (8 pcs.)", category: "Maggi & Snacks", price: "₹75", description: "Crisp bread pakoda with a spiced besan coating." },
  { name: "Aloo Pakoda (250 gm)", category: "Maggi & Snacks", price: "₹85", description: "Golden potato pakoda, fried fresh." },
  { name: "Aloo Pyaaz Pakoda (250 gm)", category: "Maggi & Snacks", price: "₹105", description: "Potato and onion pakoda with a crisp bite." },
  { name: "Mix.Veg. Sandwich (2 pcs.)", category: "Maggi & Snacks", price: "₹85", description: "Vegetable sandwich, made for a quick snack." },
  { name: "Aloo Bread Pakoda (2 pcs.)", category: "Maggi & Snacks", price: "₹90", description: "Bread pakoda filled with spiced potato." },
  { name: "Grilled Aloo Sandwich (2 pcs.)", category: "Maggi & Snacks", price: "₹80", description: "Grilled bread with a hearty potato filling." },
  { name: "Peanut Chat", category: "Maggi & Snacks", price: "₹145", description: "Peanuts tossed with fresh vegetables and chutney." },
  { name: "Sweet Corn Chat", category: "Maggi & Snacks", price: "Half ₹60 · Full ₹100", description: "Sweet corn with a bright, tangy masala." },
  { name: "Healthy Sprouts Chat", category: "Maggi & Snacks", price: "₹70", description: "Fresh sprouts with vegetables and a light dressing." },
  { name: "Healthy Veg. Upma", category: "Maggi & Snacks", price: "₹80", description: "Soft vegetable upma with a gentle tempering." },
  { name: "Bhel Puri", category: "Maggi & Snacks", price: "₹70", description: "Puffed rice, chutneys and crunchy sev." },
  { name: "Plain Rice + Dal Fry", category: "Rice, Combos & Thalis", price: "₹100", description: "Everyday rice and dal, warm and comforting." },
  { name: "Jeera Rice + Desi Ghee Dal Tadka", category: "Rice, Combos & Thalis", price: "₹150", description: "Cumin rice with a desi ghee dal tadka." },
  { name: "Plain Rice", category: "Rice, Combos & Thalis", price: "₹60", description: "Steamed rice for your sabji or dal." },
  { name: "Jeera Rice", category: "Rice, Combos & Thalis", price: "₹75", description: "Steamed rice scented with cumin." },
  { name: "Curd Rice", category: "Rice, Combos & Thalis", price: "₹105", description: "Cool, gentle curd rice with a light tempering." },
  { name: "Moongdal Khichdi with Ghee", category: "Rice, Combos & Thalis", price: "Half ₹135 · Full ₹200", description: "Comforting moong dal khichdi with ghee." },
  { name: "Maggi Masala Veg.Fried Rice", category: "Rice, Combos & Thalis", price: "₹110", description: "Vegetable fried rice with masala comfort." },
  { name: "2 Desi Ghee Paratha + Paneer Bhurji", category: "Rice, Combos & Thalis", price: "₹240", description: "Two ghee parathas with paneer bhurji." },
  { name: "2 Desi Ghee Paratha + Matar Paneer", category: "Rice, Combos & Thalis", price: "₹200", description: "Two ghee parathas with matar paneer." },
  { name: "Plain Thali", category: "Rice, Combos & Thalis", price: "₹130", description: "4 desi ghee tawa roti, rice, aloo jeera, dal fry and salad.", tag: "Everyday favourite" },
  { name: "Standard Thali", category: "Rice, Combos & Thalis", price: "₹150", description: "4 desi ghee tawa roti, rice, aloo jeera, dal fry, raita and salad.", tag: "Best seller" },
  { name: "Special Jain Thali (Without Onion & Garlic)", category: "Rice, Combos & Thalis", price: "₹220", description: "4 ghee rotis, rice, matar paneer, dal fry and salad." },
  { name: "Small Amul Butter Cube (1 pcs.)", category: "Extras & Beverages", price: "₹10", description: "A little extra butter for your paratha or roti." },
  { name: "Plain Curd", category: "Extras & Beverages", price: "₹35", description: "Cool plain curd, made for the side." },
  { name: "Boondi Raita", category: "Extras & Beverages", price: "₹65", description: "Whisked curd with boondi and seasoning." },
  { name: "Mix Veg. Raita", category: "Extras & Beverages", price: "₹80", description: "Curd with fresh vegetables and herbs." },
  { name: "Beetroot Raita", category: "Extras & Beverages", price: "₹65", description: "Cool curd with beetroot and gentle spice." },
  { name: "Masala Tadka Chach", category: "Extras & Beverages", price: "₹50", description: "Chilled chach with masala tadka." },
  { name: "Sweet Dry Fruit Lassi", category: "Extras & Beverages", price: "₹60", description: "Sweet lassi with dry fruits." },
  { name: "Kulhad Tea", category: "Extras & Beverages", price: "₹30", description: "Everyday chai in a mitti kulhad." },
  { name: "Kulhad Ginger Tea", category: "Extras & Beverages", price: "₹35", description: "Chai with fresh ginger, served in a kulhad." },
  { name: "Kulhad Tulsi Ginger Tea", category: "Extras & Beverages", price: "₹45", description: "Tulsi and ginger chai in a mitti kulhad." },
  { name: "Papad", category: "Extras & Beverages", price: "₹12", description: "Crisp papad for the side." },
  { name: "Desi Ghee Dry Fruit Suji Halwa", category: "Extras & Beverages", price: "Half ₹170 · Full ₹270", description: "Suji halwa with desi ghee and dry fruit." },
  { name: "Namkeen Daliya with Ghee", category: "Extras & Beverages", price: "₹150", description: "Savoury daliya finished with ghee." },
  { name: "Aloo Kuttu Mixed Pakoda (20 pcs.)", category: "Vrat Items", price: "₹150", description: "Kuttu and potato pakoda for vrat days." },
  { name: "Dry Fruit Mix Makhane ki Kheer (500 ml.)", category: "Vrat Items", price: "₹200", description: "Makhana kheer with dry fruit." },
  { name: "Dry Fruit Mix Sabudana Kheer (500 ml.)", category: "Vrat Items", price: "₹135", description: "Sabudana kheer with dry fruit." },
  { name: "Dry Fruit Mix Samak Ke Chawal Ki Kheer (500 ml.)", category: "Vrat Items", price: "₹130", description: "Samak rice kheer with dry fruit." },
  { name: "Sabudana Khichdi", category: "Vrat Items", price: "Half ₹130 · Full ₹250", description: "Soft sabudana khichdi with peanuts." },
  { name: "Samak ke Chawal ka Pulao", category: "Vrat Items", price: "Half ₹90 · Full ₹170", description: "Samak rice pulao for vrat days." },
  { name: "Vart Ki Sukhi Aloo ki Sabji", category: "Vrat Items", price: "Half ₹70 · Full ₹135", description: "Dry potato sabji for vrat." },
  { name: "Vart ki Aloo Gravy Sabji", category: "Vrat Items", price: "₹150", description: "Potato gravy made for vrat." },
  { name: "Vart ke liye Lauki ki Sabji", category: "Vrat Items", price: "Half ₹80 · Full ₹145", description: "Bottle-gourd sabji for vrat." },
  { name: "4 Kuttu ki Poori with Aloo Sabji", category: "Vrat Items", price: "₹170", description: "Kuttu pooris with aloo sabji." },
  { name: "Satvik Thali (No Onion Garlic)", category: "Vrat Items", price: "₹150", description: "Yellow dal, 4 tawa ghee roti, chawal, jeera aloo and green salad." },
  { name: "Vart Ki Thali", category: "Vrat Items", price: "₹270", description: "2 kuttu poori, samak pulao, dahi, aloo gravy, samak kheer and green salad.", tag: "Vrat special" },
  { name: "Mithi Dry Fruit Lassi", category: "Vrat Items", price: "₹60", description: "Sweet lassi with dry fruit." },
  { name: "Plain Curd (100 gm.)", category: "Vrat Items", price: "₹20", description: "Plain curd, 100 gram serving." },
  { name: "Plain Curd (150 gm.)", category: "Vrat Items", price: "₹35", description: "Plain curd, 150 gram serving." },
];
